### ISSUE TITLE
Java Autograder Example

### ISSUE THREAD

**Issue by jdeisenberg** [autolab/autograders-examples#12]
In this file: https://github.com/autolab/autograders-examples/blob/main/java-missing-positives/src/TestMissing.java, lines 12-17 all have `assert Missing.findSmallestMissingPositive(emptyArray)` as the left-hand side of the `==` operator.

Should they be using the different arrays defined in lines 3-8 instead?

**Comment by damianhxy** [comment]
Good catch! I will create a PR to address this.
